name: Create release

on:
  push:
    tags:
      - '*'

env:
  IMAGE_TAG: git describe --abbrev=0 --tags | sed 's/^v//'

jobs:
    build-bridge-deamon-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build Docker image
          id: build_image
          run: docker build -t tfchainbridge:${IMAGE_TAG} . -f bridge/tfchain_bridge/Dockerfile

        - name: Save Docker image
          id: save_image
          run: docker save --output tfchainbridge.tar tfchainbridge:${IMAGE_TAG}

        - name: Upload Docker image
          id: upload_image
          uses: actions/upload-artifact@v3
          with:
            name: tfchainbridge-image
            path: tfchainbridge.tar
