name: Generate benchmark weights

on:
  push:
    paths:
      - 'substrate-node/pallets/**.rs'
  workflow_dispatch:

jobs:
  benchmark-weights:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Fail if branch is main
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/development'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on main branch"
          exit 1
          
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd substrate-node
          cargo build --profile=bench --features runtime-benchmarks

      - name: Run benchmarking
        run: |
          cd substrate-node
          for weights_rs_file in ./pallets/*/src/weights.rs
          do
            rm $weights_rs_file
            pal_name=$(awk -F'pallets/|/src' '{print $2}' <<< $weights_rs_file)
            ./target/bench/tfchain benchmark pallet \
            --chain=dev \
            --wasm-execution=compiled \
            --pallet="$pal_name" \
            --extrinsic="*" \
            --steps=50 \
            --repeat=20 \
            --heap-pages=409 \
            --output ./pallets/"$pal_name"/src/weights.rs \
            --template ./.maintain/frame-weight-template.hbs
          done

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore(pallets): update benchmark `weights.rs` files ${date}'
          branch: ${{ github.ref_name }}
